### ISSUE TITLE
Ролл от большего числа к меньшему

### ISSUE THREAD

**Issue by YaMaZZZim** [C0deRang3rs/change-name-bot#37]
Можно ролить от большего числа к меньшему. 

> /roll 100-10  
и т.п.

**Comment by muuuzmich** [comment]
не уверен что это баг. Ты ролишь от какого-то числа до какого-то другого 🤔. От 10 до 100 не отличается от "от 100 до 10". Ограничение такими рамками, как по мне, не уместно

**Comment by YaMaZZZim** [comment]
> не уверен что это баг. Ты ролишь от какого-то числа до какого-то другого 🤔. От 10 до 100 не отличается от "от 100 до 10". Ограничение такими рамками, как по мне, не уместно

херли я тогда от отрицательного ролить не могу

**Comment by howHighUR** [comment]
Потому что стандартый рандомизатор жса не умеет роллить отрицательные

**Comment by howHighUR** [comment]
> > не уверен что это баг. Ты ролишь от какого-то числа до какого-то другого 🤔. От 10 до 100 не отличается от "от 100 до 10". Ограничение такими рамками, как по мне, не уместно
> 
> херли я тогда от отрицательного ролить не могу

Потому что стандартый рандомизатор жса не умеет роллить отрицательные
